---
  - hosts: ca.magicfish.dev
    become: true
    roles:
    - role: ubuntu_base
    - role: vpn_base
    - role: ca
  - hosts: vpn.magicfish.dev
    become: true
    roles:
    - role: ubuntu_base
    - role: vpn_base
    - role: vpn
  
  