  #vars_files:
    #- vars/default.yml

  #tasks:
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

  # Set up Sudo Group
    - name: Make sure we have a 'sudo' group
      group:
        name: sudo
        state: present

    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

  # User & Key Setup
    #- name: Create new user with sudo privileges.
      #user:
        #name: "{{ create_user }}"
        #state: present
        #groups: sudo
        #append: true
        #create_home: true
        #shell: /bin/bash

    #- name: Set authorized key for remote user
      #authorized_key:
        #user: "{{ create_user }}"
        #state: present
        #key: "{{ copy_local_key }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

  # Update and upgrade packages
    - name: Update apt packages
      apt: update_cache=yes

    - name: Upgrade all packages to the latest version
      apt:
         name: "*"
         state: latest

  #Install system packages
    - name: Install required system packages
      apt: name={{ sys_packages }} state=latest

 # UFW Setup
    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming